#!/usr/bin/python3
import sys

current_docid = None
total = 0

for line in sys.stdin:
    docid, count = line.strip().split('\t')
    count = int(count)

    if current_docid == docid:
        total += count
    else:
        if current_docid:
            print(f'{current_docid}\t{total}')
        current_docid = docid
        total = count

if current_docid:
    print(f'{current_docid}\t{total}')
