#!/usr/bin/python3
import sys, re, os

def termify(word):
    return re.sub('[^a-z]', '', word.lower())

for line in sys.stdin:
    docid = os.path.splitext(os.path.basename(os.getenv('map_input_file')))[0]
    for term in map(termify, line.strip().split()):
        if term:
            print(f'{docid}\t{term}\t1')
